name: Manual Server Start

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      branch:
        description: "Branch to run on"
        required: false
        default: "dev-candidate"  # Default branch
        type: string

jobs:
  start-server:
    runs-on: self-hosted  # Runs on self-hosted runner

    steps:
      - name: Checkout latest code
        run: |  # Checkout specified branch
          cd ${{secrets.SOURCE_DIR_PATH}}
          git fetch origin
          git checkout ${{ github.event.inputs.branch }}
          git pull origin ${{ github.event.inputs.branch }}

      - name: Stop Existing Server (if running)
        run: |
          cd ${{secrets.SOURCE_DIR_PATH}}
          if [ -f "server.log" ]; then
              sh stop.sh
              echo "Existing server stopped."
          else
              echo "No existing server found."
          fi

      - name: Install dependencies
        run: |
          cd ${{secrets.SOURCE_DIR_PATH}}
          npm install

      - name: Roll Over Server Log
        run: |
          cd ${{secrets.SOURCE_DIR_PATH}}
          if [ -f "server.log" ]; then
              ROLLOVER_LOG_FILE_NAME=server-$(date +"%Y-%m-%dT%H:%M:%S").log
              mv server.log ${ROLLOVER_LOG_FILE_NAME}
              echo "Server log rolled over to ${ROLLOVER_LOG_FILE_NAME}"
          fi

      - name: Start Server
        run: |
          cd ${{secrets.SOURCE_DIR_PATH}}
          LOG_FILE_NAME=${{secrets.SOURCE_DIR_PATH}} + "/server.log"
          echo "Starting server ..."
          node ${{secrets.REPO_START_FILE}} > "${LOG_FILE_NAME}" 2>&1 &
          BACKGROUND_ID = $!
           echo "Server started with PID: ${BACKGROUND_PID}"
